[package]
name = "cuecue-eval"
description = "Lowering, evaluation and export for cuecue"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dev-dependencies]
libtest-mimic = "0.8.2"

[[test]]
name = "corpus"
harness = false
